### PR TITLE
fix a small warning removing from tests /Developer/Library/Frameworks

### PR DESCRIPTION
**Pull request by sger**

### CODE REVIEW

**Comment by mickeyreiss** [comment]
Did you happen to check this change in older versions of Xcode?

**Comment by sger** [comment]
@mickeyreiss ops no

**Comment by mickeyreiss** [comment]
No worries. Can you describe the issue you were seeing in current Xcode more thoroughly? (Xcode version, maybe a screenshot?) That way we can triage this issue a bit more thoroughly.

I'd like to get to a clean build for you as quickly as possible, but at the moment, I'd also like to avoid changing our minimum requirements and Xcode support.

Thanks for your PR!

**Comment by sger** [comment]
@mickeyreiss simple warning in unit tests (i like clean things) 
screenshot 2015-10-27 12 49 03

**Pull request merged**
