### PR TITLE
Added tvOS support

### PR DESCRIPTION
**Pull request by adrum**

### CODE REVIEW

**Comment by mickeyreiss** [comment]
Exciting stuff! Thanks for sending it in. I will test and merge shortly. (If anyone else is able to provide assurance that everything works without further code changes, I'd be happy to merge sooner.)

**Comment by AvdLee** [comment]
I'm waiting for this one as well!

**Comment by Mazyod** [comment]
+1, it's a very minimal change, should be ok

**Comment by blueraz0r** [comment]
This can be closed now that #109 was merged

**Pull request closed without merging**
