### PR TITLE
Bumped Ruby version to update slather build options

### PR DESCRIPTION
**Pull request by toohotz**
Should resolve the Travis CI build issues with slather build option changes.

### CODE REVIEW

**Comment by pallzoltan** [comment]
Can anyone else than @lwdupont merge this?

**Comment by pallzoltan** [comment]
@toohotz Looks like @lwdupont won't be reviewing this, could you assign it to someone else? 
Sorry for bugging, our team is waiting to remove the last warning from our project .)) Cheers!

**Comment by toohotz** [comment]
@pallzoltan I typically try not to merge my own PRs but I agree it has been sometime and this one is relatively small to be a blocker to another PR 👍🏾

**Comment by pallzoltan** [comment]
Don't worrt, I won't tell anyone ,)

**Comment by lwdupont** [comment]
Sorry, totally missed this. I merge my own PR's, so you are good :)

**Pull request merged**
