### PR TITLE
Travis CI build fix;

### PR DESCRIPTION
**Pull request by Antondomashnev**
Hi there,
This PR addresses the issue #148 . I was following the idea of having PL prefix for each macro.
As a suggestion @mickeyreiss what do you think about treating warnings as errors?

Also, I had to specify the ruby version to be able to run travis with slather gem.

### CODE REVIEW

**Comment by Antondomashnev** [comment]
@mickeyreiss weird, but one of three jobs was failed. Don't know the reason yet.

**Comment by Lutzifer** [comment]
Looks more like a travis problem to me, than an actual problem with the code, can we get this merged?

**Comment by lkraider** [comment]
Already fixed with the merge of #154 (which has essentially the same changes). A new PR with travis fixes would be nice.

**Comment by Antondomashnev** [comment]
@lkraider do you have any idea what could be with Travis?

**Comment by lkraider** [comment]
Seems Ruby 2.3 binary is not available (we are using 10.9 env, maybe bump to 10):
https://rvm.io/binaries/osx/10.9/x86_64/

I think we need to:
- [ ] bump env to 10.11
- [ ] specify ruby 2.2 in .ruby-version
- [ ] build ruby 2.3 from source in before_install

references:
https://github.com/rvm/rvm/issues/3686
https://github.com/travis-ci/travis-ci/issues/5361

**Comment by Antondomashnev** [comment]
@lkraider thanks, I'll double check the travis error and will try to submit an update.

**Comment by Antondomashnev** [comment]
Hi folks, the Travis build is fixed, I'll rename the PR.

**Comment by lkraider** [comment]
Awesome, great work!

**Comment by mhillebrand** [comment]
I would love to see this get merged.

**Comment by mhillebrand** [comment]
Sweet! Thanks, @mickeyreiss. No more warnings when using Carthage. 😄 Now what about creating a new tag, since that's what Carthage looks for by default?

**Comment by mickeyreiss** [comment]
@mhillebrand Yep - I think it's about time to cut the release 📦 🦆 

BTW - @mhillebrand @lkraider @Lutzifer I'd to enlist your help maintaining the library. If you're interested, please contact me by email or on twitter.

**Comment by mhillebrand** [comment]
@mickeyreiss I'd be honored. PureLayout kicks ass. Maybe I could help convert the code to Swift?

**Comment by Antondomashnev** [comment]
@mickeyreiss I would also love to help converting it to swift 😄

**Comment by Lutzifer** [comment]
@mickeyreiss As I do not know, how much time i will be able to contribute I will keep doing PRs if necessary 😉

**Comment by lkraider** [comment]
@mickeyreiss Would love to contribute more, we use PureLayout in most our projects @nKey.

**Pull request merged**
