### PR TITLE
Fix compiler warnings about enum comparison

### PR DESCRIPTION
**Pull request by tomhamming**
This silences [`-Wenum-compare-switch`](https://clang.llvm.org/docs/DiagnosticsReference.html#wenum-compare-switch). Clang documentation says it's on by default, so I'm not sure why it's not showing up in the PureLayout example projects, but it is in mine. It's harmless in this case, and easy to silence.

Alternatively it could use the `ALAttribute` values (i.e. `ALAttributeLeft` instead of `ALEdgeLeft`).

### CODE REVIEW

**Comment by tomhamming** [comment]
Should I be trying to fix the CI build here? It looks like it's complaining about some configuration issue...

**Comment by toohotz** [comment]
I will look into this one tonight though I feel more inclined to lean towards using the `ALAtributeValue` as opposed to type casting the `ALEdgeValue`.  I see a previous PR that was merged in also was failing the CI tests so would be nice to have that fixed in this PR.  I'll try to have this out by tomorrow.

**Comment by toohotz** [comment]
So upon double checking, there exists an `ALAttribute` type for all the possible case types that we care about so the better fix would be to use those values as opposed to type casting the `ALEdge` and also `ALDimension`, axis, etc so that if there are changes to those other types in the future, this code would be impact independent of those changes.

So swapping all the case types from `ALDimensionHeight` to `ALAttributeHeight` as one example, would be the best solve as in the `PureLayoutDefines.h` where the enum itself is defined, it is already doing the underlying mapping for us.

**Comment by tomhamming** [comment]
That makes sense. Do you want me to make that change?

**Comment by toohotz** [comment]
Please and thank you then I'll get this merged in.  Regarding the CI builds failing, that can be addressed in another PR.

**Comment by lwdupont** [comment]
Thanks @toohotz  👍

**Pull request merged**
