### PR TITLE
Fix carthage build error on tvOS

### PR DESCRIPTION
**Pull request by arsonik**
as referenced here :
https://github.com/PureLayout/PureLayout/issues/146

### CODE REVIEW

**Comment by Lutzifer** [comment]
Can we get this merged?
Recreating the Framework Target as a tvOS Framework from scratch yielded similar results.

**Comment by Lutzifer** [comment]
@arsonik Could you integrate the fixes from #153 to fix the build?

**Comment by arsonik** [comment]
sorry dont really have time for the next couple of days :\

**Comment by Lutzifer** [comment]
#163 tries to replace this

**Comment by Lutzifer** [comment]
We can close this, then

**Pull request closed without merging**
